const { SlashCommandBuilder } = require('discord.js');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('deliver')
    .setDescription('Send the private server link to the buyer')
    .addStringOption(opt => 
      opt.setName('order')
        .setDescription('Order ID (e.g. #1027)')
        .setRequired(true))
    .addUserOption(opt => 
      opt.setName('user')
        .setDescription('Buyer\'s Discord user')
        .setRequired(true))
    .addStringOption(opt => 
      opt.setName('link')
        .setDescription('Private server link')
        .setRequired(true)),

  async execute(interaction) {
    const orderId = interaction.options.getString('order');
    const user = interaction.options.getUser('user');
    const link = interaction.options.getString('link');

    try {
      await user.send(
        `📡 **Your Private Server is Ready**\n\n` +
        `🧾 Order \`${orderId}\` is now ready for delivery.\n` +
        `🔗 Join the private server now:\n${link}\n\n` +
        `📦 Our delivery bot will meet you in-game to hand over your item.\n\n` +
        `💬 This message was generated by **Bloom Haven AutoOrder v2.1**`
      );

      await interaction.reply({ content: `✅ Sent delivery link for order ${orderId} to <@${user.id}>.`, ephemeral: true });
    } catch (err) {
      console.error('❌ DM failed:', err);
      await interaction.reply({ content: `❌ Couldn't DM the user.`, ephemeral: true });
    }
  }
};
