const { SlashCommandBuilder } = require('discord.js');
const fs = require('fs');
const path = require('path');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('markpaid')
    .setDescription('Mark an order as paid and notify the buyer')
    .addStringOption(opt =>
      opt.setName('order')
        .setDescription('Order ID (e.g. 1027)')
        .setRequired(true))
    .addStringOption(opt =>
      opt.setName('item')
        .setDescription('Item purchased (e.g. Raccoon, Sheckles)')
        .setRequired(true))
    .addUserOption(opt =>
      opt.setName('user')
        .setDescription('Buyer\'s Discord user')
        .setRequired(true)),

  async execute(interaction) {
    const orderId = interaction.options.getString('order');
    const itemName = interaction.options.getString('item');
    const user = interaction.options.getUser('user');

    const ordersPath = path.join(__dirname, '..', 'orders.json');
    let orders = {};
    if (fs.existsSync(ordersPath)) {
      orders = JSON.parse(fs.readFileSync(ordersPath, 'utf8'));
    }

    orders[orderId] = {
      item: itemName,
      userId: user.id,
      logMessageId: orders[orderId]?.logMessageId || null
    };

    fs.writeFileSync(ordersPath, JSON.stringify(orders, null, 2));

    try {
      await user.send(
        `💵 **Payment Confirmed Automatically**\n\n` +
        `🧾 Order \`${orderId}\` for **${itemName}** has been marked as paid.\n` +
        `📦 Your item is now queued for in-game delivery.\n` +
        `⏳ You’ll receive the private server link shortly.\n\n` +
        `💬 This message was generated by **Bloom Haven AutoOrder v2.1**`
      );
    } catch (err) {
      console.warn(`❌ Couldn't DM user: ${err}`);
    }

    // Try editing the order log message
    try {
      const logChannelId = '1397212138753495062';
      const logChannel = await interaction.client.channels.fetch(logChannelId);
      const messageId = orders[orderId]?.logMessageId;

      if (logChannel && messageId) {
        const message = await logChannel.messages.fetch(messageId);
        const embed = message.embeds[0];
        const updatedFields = embed.fields.map(field => {
          if (field.name === '💳 Payment') {
            return { name: '💳 Payment', value: '✅ Payment Confirmed', inline: true };
          }
          return field;
        });

        await message.edit({
          embeds: [{
            ...embed.toJSON(),
            fields: updatedFields
          }]
        });
      }
    } catch (e) {
      console.error('❌ Could not update order log message:', e);
    }

    await interaction.reply({ content: `✅ Order ${orderId} marked as paid and saved as "${itemName}".`, ephemeral: true });
  }
};
