const { SlashCommandBuilder } = require('discord.js');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('markpaid')
    .setDescription('Mark an order as paid and notify the buyer')
    .addStringOption(opt => 
      opt.setName('order')
        .setDescription('Order ID (e.g. #1027)')
        .setRequired(true))
    .addUserOption(opt => 
      opt.setName('user')
        .setDescription('Buyer\'s Discord user')
        .setRequired(true)),

  async execute(interaction) {
    const orderId = interaction.options.getString('order');
    const user = interaction.options.getUser('user');

    try {
      await user.send(
        `💵 **Payment Confirmed Automatically**\n\n` +
        `🧾 Order \`${orderId}\` has been marked as paid.\n` +
        `📦 Your item is now queued for in-game delivery.\n` +
        `⏳ You’ll receive the private server link shortly.\n\n` +
        `💬 This message was generated by **Bloom Haven AutoOrder v2.1**`
      );

      await interaction.reply({ content: `✅ Order ${orderId} marked as paid and DM sent to <@${user.id}>.`, ephemeral: true });
    } catch (err) {
      console.error('❌ DM failed:', err);
      await interaction.reply({ content: `❌ Couldn't DM the user.`, ephemeral: true });
    }
  }
};
